import js from "@eslint/js";
import reactPlugin from "eslint-plugin-react";
import reactHooksPlugin from "eslint-plugin-react-hooks";
import prettierConfig from "eslint-config-prettier";

export default [
  js.configs.recommended,
  prettierConfig,
  {
    files: ["frontend/src/**/*.{js,jsx}"],
    plugins: {
      react: reactPlugin,
      "react-hooks": reactHooksPlugin,
    },
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: "module",
      parserOptions: { ecmaFeatures: { jsx: true } },
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        fetch: "readonly",
        URL: "readonly",
        Blob: "readonly",
        performance: "readonly",
        confirm: "readonly",
        alert: "readonly",
        crypto: "readonly",
        Date: "readonly",
        Promise: "readonly",
        Math: "readonly",
        HTMLImageElement: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        Audio: "readonly",
        HTMLElement: "readonly",
        FileReader: "readonly",
        FormData: "readonly",
        indexedDB: "readonly",
        IDBKeyRange: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        atob: "readonly",
        btoa: "readonly",
        location: "readonly",
        history: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        AbortController: "readonly",
        MediaStream: "readonly",
        SubtleCrypto: "readonly",
        prompt: "readonly",
        URLSearchParams: "readonly",
        File: "readonly",
        Notification: "readonly",
        Uint8Array: "readonly",
        ArrayBuffer: "readonly",
        Map: "readonly",
        Set: "readonly",
        WeakMap: "readonly",
        Symbol: "readonly",
        Proxy: "readonly",
        Reflect: "readonly",
        globalThis: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-console": "off",
      "react/react-in-jsx-scope": "off",
      "react/prop-types": "off",
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
      "no-empty": "off",
    },
    settings: { react: { version: "detect" } },
  },
  {
    files: ["**/*.js"],
    ignores: ["frontend/**"],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: "module",
      globals: {
        process: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        Buffer: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        Date: "readonly",
        Promise: "readonly",
        Math: "readonly",
        URL: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-console": "off",
    },
  },
  {
    ignores: ["node_modules/", "public/", "dist/", "*.cjs"],
  },
];
