/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chat/relationship/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Relationship state between viewer and target (for FriendButton / MessageButton rendering)
         * @description Returns the cached state the UI needs to pick the right
         *     button. `self:true` hides the buttons. `blocked` hides them.
         *     `canMessage` gates the Message button specifically
         *     (derived from target's `allow_messages_from` policy).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Relationship state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RelationshipState"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/relationships/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch relationship lookup (for list pages — leaderboard, event registrants)
         * @description Pre-warms the client-side relationship cache for a list of
         *     users in ONE request. The leaderboard fires this on mount so
         *     hovering any row renders the hovercard instantly. Capped at
         *     100 ids per call; over-cap rejected with 400.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        userIds: string[];
                    };
                };
            };
            responses: {
                /** @description Map of userId → RelationshipState */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: components["schemas"]["RelationshipState"];
                        };
                    };
                };
                /** @description Validation failed (empty list, >100 ids, or invalid uuid) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/friends/request/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Withdraw a pending friend request I (the viewer) sent
         * @description 404 if no matching pending row exists — the UI can blindly call and refetch.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        recipientId: string;
                    };
                };
            };
            responses: {
                /** @description Cancelled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No pending request to cancel */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/friends/{friendshipId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove an accepted friendship (unfriend)
         * @description Works for either side of the friendship. Doesn't delete
         *     conversation history or messages — that stays in case the
         *     pair re-friends later. 400 if the row is still pending
         *     (use cancel endpoint for that); 403 if caller is neither
         *     party; 404 if the id doesn't exist.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    friendshipId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unfriended */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Friendship is still pending — use cancel instead */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Caller is neither the requester nor the recipient */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Friendship not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rich profile aggregate (header + counts + access + relationship)
         * @description Single payload powering the `/profile/:userId` page. Respects
         *     `profile_visibility` — returns a minimal private card
         *     (`profile.isPrivate=true`) when the viewer isn't allowed.
         *     Email is only included when `access.isSelf=true`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profile aggregate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            profile?: components["schemas"]["PublicProfile"] | components["schemas"]["PrivateProfileCard"];
                            access?: components["schemas"]["ProfileAccess"];
                            relationship?: components["schemas"]["RelationshipState"];
                        };
                    };
                };
                /** @description User not in viewer's org (or doesn't exist — no distinction) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/friends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Paginated friend list with mutual-friend flags
         * @description Each row is flagged `isMutual:true` when the viewer is also
         *     friends with that person — the Friends tab + hovercard use
         *     this to highlight shared connections. When the target's
         *     `show_friend_list=false` and viewer is not self, returns
         *     `{ friends: [], hiddenByUser: true }`.
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated friends */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            friends?: {
                                /** Format: uuid */
                                id?: string;
                                name?: string;
                                title?: string | null;
                                xp?: number | null;
                                avatar_emoji?: string | null;
                                avatar_color?: string | null;
                                isMutual?: boolean;
                            }[];
                            total?: number;
                            page?: number;
                            limit?: number;
                            hiddenByUser?: boolean;
                        };
                    };
                };
                /** @description Profile is private (not an accepted friend) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Merged timeline of event registrations + achievement unlocks
         * @description Sorted descending by timestamp. Respects `show_activity_feed`
         *     — returns `hiddenByUser:true` when the viewer isn't allowed
         *     (non-self + target has activity hidden).
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Activity page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: {
                                /** @enum {string} */
                                kind?: "event" | "achievement";
                                /** Format: date-time */
                                at?: string;
                                data?: {
                                    [key: string]: unknown;
                                };
                            }[];
                            page?: number;
                            limit?: number;
                            hasMore?: boolean;
                            hiddenByUser?: boolean;
                        };
                    };
                };
                /** @description Profile is private */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/mutual-friends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Intersection of viewer's friends and target's friends
         * @description Powers the Overview tab's "You and N others share..." avatar
         *     strip. Capped at 50 returned rows; self-view returns
         *     `{ mutual:[], count:0 }` (nothing useful to show).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Mutual friends */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            mutual?: {
                                /** Format: uuid */
                                id?: string;
                                name?: string;
                                avatar_emoji?: string | null;
                                avatar_color?: string | null;
                            }[];
                            count?: number;
                        };
                    };
                };
                /** @description Profile is private */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Always 200 if the Node process is running. Sub-ms — does no I/O.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status?: string;
                            uptimeSec?: number;
                            /** Format: date-time */
                            startedAt?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Checks Supabase connectivity + critical env vars. Returns 200
         *     when ready to serve, 503 with a per-check breakdown otherwise.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All checks passed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description At least one check failed */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example not_ready */
                            status?: string;
                            checks?: {
                                [key: string]: {
                                    ok?: boolean;
                                    reason?: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/csrf-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mint a CSRF token + set the paired cookie
         * @description Call once on app boot. Stash the returned `csrfToken` and put
         *     it in the `x-csrf-token` header on every subsequent mutating
         *     request. The frontend `axios` interceptor handles this
         *     automatically.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token + paired cookie set */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            csrfToken?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with email + password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Logged in; sets session cookie */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            user?: components["schemas"]["SessionUser"];
                            /** @example /dashboard */
                            redirectTo?: string;
                        };
                    };
                };
                400: components["responses"]["Validation"];
                /** @description Bad credentials, or code: EMAIL_NOT_VERIFIED */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Account suspended or organisation suspended */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new account
         * @description If `invite_token` is present, the new student inherits the
         *     invitation's org + role. Otherwise the controller falls back
         *     to the FIRST org in the system (current single-org dev
         *     behaviour; should become invite-required in a real multi-
         *     tenant deploy).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                        name?: string;
                        invite_token?: string;
                    };
                };
            };
            responses: {
                /** @description Account created (email verification pending) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["Validation"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current session info */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Always 200 — body indicates whether logged in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            loggedIn?: boolean;
                            user?: components["schemas"]["SessionUser"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the current session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session destroyed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payment/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List subscription plans
         * @description Public — used by the pricing page.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Plan list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payment/create-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a checkout (creates a Razorpay order)
         * @description Idempotent if the client sends an `Idempotency-Key` header
         *     (Phase 10.2). Two calls with the same key return the same
         *     order; without the header, every call creates a new order.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Client-supplied unique id (8–200 chars) */
                    "Idempotency-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example pro */
                        plan_name: string;
                    };
                };
            };
            responses: {
                /** @description Razorpay order created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            order_id?: string;
                            /** @description in paise (INR * 100) */
                            amount?: number;
                            /** @example INR */
                            currency?: string;
                            plan_name?: string;
                            plan_display?: string;
                            /** @description Razorpay public key for the frontend SDK */
                            key_id?: string;
                        };
                    };
                };
                400: components["responses"]["Validation"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["RateLimited"];
                /** @description Razorpay not configured */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payment/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify a payment + upgrade the org's plan */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        razorpay_order_id: string;
                        razorpay_payment_id: string;
                        razorpay_signature: string;
                    };
                };
            };
            responses: {
                /** @description Verified + plan upgraded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad signature, malformed payload, or unknown order */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payment/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Razorpay webhook (server-to-server)
         * @description Razorpay POSTs payment lifecycle events here. Validated by
         *     HMAC against `RAZORPAY_WEBHOOK_SECRET`. Bypasses CSRF +
         *     session — Razorpay can't carry either.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Acknowledged */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid signature / malformed body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/registrations/{regId}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Student submits their UPI transaction reference after paying
         * @description Flips the registration's payment_status from `pending` (or
         *     `rejected`) to `submitted`. Only callable by the user who owns
         *     the registration. 409 if already paid, 400 if the event is
         *     free.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    regId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description UPI transaction reference from the bank/UPI app */
                        paymentRef: string;
                    };
                };
            };
            responses: {
                /** @description Submitted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Free event */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not your registration */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Registration not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Already paid */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin/teacher — list registrations with payment status for reconciliation */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event summary + registrations list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            event?: {
                                /** Format: uuid */
                                id?: string;
                                is_paid?: boolean;
                                price_paise?: number;
                            };
                            registrations?: {
                                /** Format: uuid */
                                id?: string;
                                /** Format: uuid */
                                user_id?: string;
                                /** @enum {string} */
                                payment_status?: "not_required" | "pending" | "submitted" | "paid" | "rejected";
                                payment_ref?: string | null;
                                /** Format: date-time */
                                paid_at?: string | null;
                                rejection_reason?: string | null;
                                students?: {
                                    name?: string;
                                    email?: string;
                                };
                            }[];
                        };
                    };
                };
                /** @description Not a teacher/admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Event not in this org */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/registrations/{regId}/mark-paid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin/teacher marks a submitted payment as verified
         * @description Idempotent — calling on an already-paid registration returns
         *     200 with `alreadyPaid: true` and does NOT rewrite paid_at.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    regId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Marked paid (or already paid — check alreadyPaid flag) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Free event or validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not a teacher/admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Registration not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/registrations/{regId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin/teacher rejects a submitted payment with a reason
         * @description The reason is shown to the student on the event page so they
         *     know why and can resubmit. Cannot reject an already-paid
         *     registration (409) — escalate to super_admin to reverse.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    regId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reason: string;
                    };
                };
            };
            responses: {
                /** @description Rejected */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation failed or free event */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not a teacher/admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Registration not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Already verified as paid */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Platform-wide aggregate counts (homepage hero)
         * @description Public — no auth, no CSRF, intentionally cross-org.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Counts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            members?: number | null;
                            challenges?: number | null;
                            events?: number | null;
                            submissions?: number | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Standard error response shape — every 4xx/5xx body conforms.
         * @example {
         *       "error": "Validation failed",
         *       "code": "VALIDATION_FAILED",
         *       "requestId": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
         *       "issues": [
         *         {
         *           "path": "email",
         *           "message": "must be a valid email"
         *         }
         *       ]
         *     }
         */
        ErrorEnvelope: {
            error: string | Record<string, never>;
            /**
             * @description Stable machine-readable code. See Phase 9.2.
             * @enum {string}
             */
            code?: "BAD_REQUEST" | "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "PAYLOAD_TOO_LARGE" | "UNPROCESSABLE" | "RATE_LIMITED" | "INTERNAL" | "BAD_GATEWAY" | "SERVICE_UNAVAILABLE" | "VALIDATION_FAILED" | "CSRF_INVALID" | "EMAIL_NOT_VERIFIED";
            /**
             * Format: uuid
             * @description Echo of the response's `x-request-id` header.
             */
            requestId?: string;
            /** @description Present on code: VALIDATION_FAILED responses. */
            issues?: {
                /** @example email */
                path?: string;
                /** @example must be a valid email */
                message?: string;
            }[];
        };
        SessionUser: {
            /** Format: uuid */
            id?: string;
            /** Format: email */
            email?: string;
            name?: string;
            /** @enum {string} */
            role?: "student" | "teacher" | "admin" | "super_admin";
            /** Format: uuid */
            org_id?: string | null;
            org_name?: string | null;
            org_slug?: string | null;
            /** @example #7c3aed */
            org_color?: string;
            /** @example free */
            org_plan?: string;
            is_active?: boolean;
        };
        /**
         * @description Shape returned by /api/chat/relationship/:id and embedded in
         *     the profile aggregate. Single source of truth for which
         *     button the UI renders.
         */
        RelationshipState: {
            /** @description true when viewer is looking at their own id */
            self: boolean;
            /** @enum {string|null} */
            friendship: "pending_sent" | "pending_received" | "accepted" | null;
            blocked: false | ("by_me" | "by_them");
            /** @description Derived from target's allow_messages_from + friendship + block */
            canMessage: boolean;
            /** Format: uuid */
            friendshipId: string | null;
        };
        /**
         * @description Per-viewer access flags for the target profile. Every
         *     /api/users/:id/* endpoint returns these (directly or via the
         *     profile aggregate) so the frontend can render consistent
         *     disabled-tab / private-card states.
         */
        ProfileAccess: {
            canViewProfile?: boolean;
            canViewActivityFeed?: boolean;
            canViewFriendList?: boolean;
            isSelf?: boolean;
            isFriend?: boolean;
            /** @enum {string} */
            reason?: "self" | "public" | "friend" | "private" | "blocked";
        };
        PublicProfile: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @description Only present when access.isSelf=true */
            email?: string;
            xp?: number;
            weekly_xp?: number;
            title?: string | null;
            bio?: string | null;
            avatar_emoji?: string | null;
            avatar_color?: string | null;
            avatar_config?: Record<string, never> | null;
            role?: string;
            department?: string | null;
            /** Format: date-time */
            created_at?: string;
            friend_count?: number;
            achievement_count?: number;
        };
        /**
         * @description Shape returned when the viewer isn't allowed to see the
         *     full profile. Only a few safe fields so hovercards + name
         *     displays across the app still render something.
         */
        PrivateProfileCard: {
            /** Format: uuid */
            id?: string;
            name?: string;
            avatar_emoji?: string | null;
            avatar_color?: string | null;
            /** @enum {boolean} */
            isPrivate?: true;
        };
    };
    responses: {
        /** @description Validation failed */
        Validation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Login required */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated but not allowed (wrong role / wrong org / missing CSRF) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource doesn't exist (or isn't visible to this caller) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Too many requests */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        csrfTokenHeader: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
